name: fenix_app_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.8.0
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
